# Generated by Django 2.2.2 on 2019-09-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0010_lake_has_resources'),
        ('plants', '0002_revise_native_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantobservation',
            unique_together={('lake', 'plant', 'observation_date')},
        ),
    ]
