# Generated by Django 2.2.4 on 2019-09-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_observation_unique_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedPlantObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Initialized'), (2, 'Loading'), (3, 'Completed'), (4, 'Error')], default=1)),
                ('source', models.CharField(choices=[('CLR', 'Center for Lakes and Reservoir'), ('IMAP', 'iMapInvasives')], max_length=8)),
                ('datafile', models.FileField(upload_to='')),
                ('output', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'imported plant datafile',
                'ordering': ('-created_on', '-updated_on'),
            },
        ),
    ]
