# Generated by Django 2.2.2 on 2019-09-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_observation_unique_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantobservation',
            options={'ordering': ('-observation_date',)},
        ),
        migrations.AlterField(
            model_name='plant',
            name='is_native',
            field=models.NullBooleanField(choices=[(True, 'Native'), (False, 'Non-native'), (None, 'Unknown')], default=None),
        ),
    ]
