

STATUS_PENDING = 1
STATUS_NON_DETECT = 2
STATUS_DETECT = 3
STATUS_CHOICES = (
    (STATUS_PENDING, 'Pending'),
    (STATUS_NON_DETECT, 'Non-detect'),
    (STATUS_DETECT, 'Detect'),
)

IMPORT_STATUS_INITIALIZED = 1
IMPORT_STATUS_LOADING = 2
IMPORT_STATUS_COMPLETED = 3
IMPORT_STATUS_ERROR = 4
IMPORT_STATUS_CHOICES = (
    (IMPORT_STATUS_INITIALIZED, 'Initialized'),
    (IMPORT_STATUS_LOADING, 'Loading'),
    (IMPORT_STATUS_COMPLETED, 'Completed'),
    (IMPORT_STATUS_ERROR, 'Error'),
)
