version: '3'
services:
  app:
    image: ghcr.io/psu-oit-arc/aol-backend/app-prod:1.6.10
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
      - APP_USER_ID=1101
      - APP_GROUP_ID=1101
