version: "3"

secrets:
  SecretKey:
    file: docker/secret_key.txt
  DBPassword:
    file: docker/db_password.txt

networks:
  default:
    driver: bridge
    ipam:
      config:
        # this value is a soft-reservation of the subnet in
        # order to reduce friction w.r.t. a given local docker
        # environment and project configuration.
        # 
        # if you encounter network definition conflicts, change
        # the value below and revise its use in 'local.*.cfg'.
        - subnet: 172.20.0.0/16

services:
  postgres:
    image: kartoza/postgis:11.0-2.5
    networks:
      - default
    ports:
      - 5432:5432
    environment:
      # In some cases, the logic present in the kartoza/postgis
      # entrypoint may fail to recognize that this database already
      # exists when the container volume has already such a database
      # present; in this case, comment the 'POSTGRES_DBNAME' entry
      # in order to succesfully boot the container.
      - POSTGRES_USER=aol
      - POSTGRES_PASS=aol
      - POSTGRES_DBNAME=aol
      - ALLOW_IP_RANGE=172.20.0.0/16
    volumes:
      - /vol/aol/postgres:/var/lib/postgresql
      - /vol/aol/dumps:/archive

  rabbitmq:
    image: rabbitmq:3-alpine
    networks:
      - default
    volumes:
      - /vol/aol/rabbitmq:/var/lib/rabbitmq
    # override hostname to prevent reinitialization of data
    # on container delete/init cycle.
    #   Refs: https://github.com/docker-library/rabbitmq/issues/106#issuecomment-241882358
    hostname: 'rabbitmq-dev'
    user: '1000'  # adjust uid with a local account uid

  app:
    build: docker
    user: aol
    environment:
      - APP_CONFIG=app.docker.yml
      - APP_SERVICE=wsgi
      - EMCEE_CMD_ENV=docker
    networks:
      - default
    ports:
      - 8000:8000
    volumes:
      - ./:/webapps/aol
      - /vol/aol/static:/static
      - /vol/aol/media:/media
    depends_on:
      - postgres
      - rabbitmq
    secrets:
      - SecretKey
      - DBPassword

  celery:
    build: docker
    environment:
      - APP_CONFIG=app.docker.yml
      - APP_SERVICE=celery
      - EMCEE_CMD_ENV=docker
    networks:
      - default
    volumes:
      - ./:/webapps/aol
      - /vol/aol/media:/media
    depends_on:
      - app
    secrets:
      - SecretKey
      - DBPassword
