version: "3"

secrets:
  SecretKey:
    file: docker/secret_key.txt
  DBPassword:
    file: docker/db_password.txt

networks:
  default:
    driver: bridge

services:
  postgres:
    image: kartoza/postgis:11.0-2.5
    networks:
      - default
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      # In some cases, the logic present in the kartoza/postgis
      # entrypoint may fail to recognize that this database already
      # exists when the container volume has already such a database
      # present; in this case, comment the 'POSTGRES_DBNAME' entry
      # in order to succesfully boot the container.
      - POSTGRES_USER=aol
      - POSTGRES_PASS=aol
      - POSTGRES_DBNAME=aol
      - ALLOW_IP_RANGE=172.20.0.0/16
    volumes:
      - ./volumes/postgres:/var/lib/postgresql
      - ./volumes/dumps:/archive
    # user: '1000'  # adjust uid with a local account uid

  rabbitmq:
    image: rabbitmq:3-alpine
    networks:
      - default
    ports:
      - "127.0.0.1:5672:5672"
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    # override hostname to prevent reinitialization of data
    # on container delete/init cycle.
    #   Refs: https://github.com/docker-library/rabbitmq/issues/106#issuecomment-241882358
    hostname: 'rabbitmq-dev'
    user: '1000'  # adjust uid with a local account uid

  app:
    build:
      context: docker
      # args:
      #   - APP_USER_ID=  # adjust uid/gid with local account
      #   - APP_GROUP_ID=
    environment:
      - EMCEE_CMD_ENV=docker
      - APP_SERVICE=wsgi
    networks:
      - default
    ports:
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./:/app
    depends_on:
      - postgres
      - rabbitmq
    secrets:
      - SecretKey
      - DBPassword
    user: '1000:1000'  # adjust uid with a local account uid

  celery:
    build:
      context: docker
      # args:
      #   - APP_USER_ID=  # adjust uid/gid with local account
      #   - APP_GROUP_ID=
    environment:
      - EMCEE_CMD_ENV=docker
      - APP_SERVICE=celery
    networks:
      - default
    volumes:
      - ./volumes/media:/media
      - ./:/app
    depends_on:
      - app
    secrets:
      - SecretKey
      - DBPassword
    user: '1000:1000'  # adjust uid with a local account uid