version: '3.7'
networks:
  overlay:
    driver: overlay
    attachable: true
services:
  rabbitmq:
    image: rabbitmq:3-alpine
    networks:
    - overlay
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/passwd:/etc/passwd:ro
    - /vol/www/aol-backend/services/rabbitmq:/var/lib/rabbitmq
    logging:
      driver: json-file
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
    hostname: rabbitmq-prod
    user: 1101:1101
  app:
    image: ghcr.io/psu-oit-arc/aol-backend/app-prod:1.6.6
    networks:
    - overlay
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/passwd:/etc/passwd:ro
    - /vol/store/media:/vol/store/media
    - /vol/www/aol-backend:/vol/www/aol-backend
    - ./:/app
    - ./uwsgi:/uwsgi
    environment:
    - EMCEE_CMD_ENV=prod
    - APP_SERVICE=wsgi
    logging:
      driver: json-file
    deploy:
      replicas: 1
    user: aol-backend:aol-backend
  celery:
    image: ghcr.io/psu-oit-arc/aol-backend/app-prod:1.6.6
    networks:
    - overlay
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/passwd:/etc/passwd:ro
    - /vol/store/media:/vol/store/media
    - /vol/www/aol-backend:/vol/www/aol-backend
    - ./:/app
    environment:
    - EMCEE_CMD_ENV=prod
    - APP_SERVICE=celery
    logging:
      driver: json-file
    deploy:
      replicas: 1
    depends_on:
    - rabbitmq
    user: aol-backend:aol-backend
  scheduler:
    image: ghcr.io/psu-oit-arc/aol-backend/app-prod:1.6.6
    networks:
    - overlay
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/passwd:/etc/passwd:ro
    - /vol/store/media:/vol/store/media
    - /vol/www/aol-backend:/vol/www/aol-backend
    - ./:/app
    environment:
    - EMCEE_CMD_ENV=prod
    - APP_SERVICE=scheduler
    logging:
      driver: json-file
    deploy:
      replicas: 1
    depends_on:
    - rabbitmq
    user: aol-backend:aol-backend
  proxy:
    image: nginx:stable
    networks:
    - overlay
    ports:
    - target: 80
      published: 80
      protocol: tcp
      mode: host
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /vol/www/aol-backend/active/nginx/aol-backend.conf:/etc/nginx/conf.d/default.conf
    - /vol/www/aol-backend/active/nginx/host_defaults.conf:/etc/nginx/host_defaults.conf
    - /vol/www/aol-backend/active/nginx/server_defaults.conf:/etc/nginx/server_defaults.conf
    - /vol/www/aol-backend/static:/static
    - /vol/store/media:/media
    logging:
      driver: json-file
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
    depends_on:
    - app
