AWSTemplateFormatVersion: '2010-09-09'
Description: Resource stack for Atlas of Oregon Lakes
Resources:
  AppRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20190607/iam/application_role.template.yml
      Parameters:
        Name: aol-backend
        VpcStackName: vpc-stage
  Host:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20190607/ec2/private_host/private_host.template.yml
      Parameters:
        ImageId: ami-d2f06baa
        ImageDistribution: amazon2
        HostName: !GetAtt 'AppRole.Outputs.Name'
        VpcStackName: !GetAtt 'AppRole.Outputs.VpcStackName'
        IAMAppRoleName: !GetAtt 'AppRole.Outputs.RoleName'
        ExternalZoneName: stage.wdt.pdx.edu
        InternalZoneName: stage-internal
        UseEFSFilesystem: true
        EbsVolumeId: !GetAtt 'Volume.Outputs.EbsVolume'
  Networking:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20190607/ec2/private_host/networking.template.yml
      Parameters:
        EC2Instance: !GetAtt 'Host.Outputs.InstanceId'
        PrivateIp: !GetAtt 'Host.Outputs.PrivateIP'
        DnsHostName: !GetAtt 'AppRole.Outputs.Name'
        VpcStackName: !GetAtt 'AppRole.Outputs.VpcStackName'
        ExternalZoneName: !GetAtt 'Host.Outputs.ExternalZoneName'
        InternalZoneName: !GetAtt 'Host.Outputs.InternalZoneName'
        ELBListenerPriority: !Ref 'ELBListenerPriority'
        ListenOn80: true
  PostgreSQL:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20190607/rds/postgres.template.yml
      Parameters:
        VpcStackName: !GetAtt 'AppRole.Outputs.VpcStackName'
        AvailabilityZone: us-west-2a
        DBInstanceName: aol-backend-stage
        DBUsername: aol_backend_l
        DBPassword: !Ref 'DBPassword'
        EC2SecurityGroupId: !GetAtt 'Host.Outputs.EC2SecurityGroup'
  Volume:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20190607/ec2/ebs/volume.template.yml
      Parameters:
        Name: aol-backend-stage
        AvailabilityZone: us-west-2a
Parameters:
  ELBListenerPriority:
    Type: String
    Description: Mechanism for declaring ELBListenerPriority
  DBPassword:
    Type: String
    Description: Mechanism for declaring DBPassword
