

DOCUMENT_TYPE_OTHER = 0
DOCUMENT_TYPE_MAP = 1
DOCUMENT_TYPE_BATHYMETRY = 2
DOCUMENT_TYPE_BASIN_STATISTICS = 3
DOCUMENT_TYPE_ATLAS_PRINT_PAGE = 4
DOCUMENT_TYPE_CHOICES = (
    (DOCUMENT_TYPE_MAP, "Map"),
    (DOCUMENT_TYPE_BATHYMETRY, "Bathymetry"),
    (DOCUMENT_TYPE_BASIN_STATISTICS, "Basin Statistics"),
    (DOCUMENT_TYPE_ATLAS_PRINT_PAGE, "Atlas of Oregon Lakes Page"),

    (DOCUMENT_TYPE_OTHER, "Other")
)
