

WATERBODY_TYPE_UNKNOWN = 0
WATERBODY_TYPE_ESTUARY = 493
WATERBODY_TYPE_ICEMASS = 378
WATERBODY_TYPE_LAKE_POND = 390
WATERBODY_TYPE_PLAYA = 361
WATERBODY_TYPE_RESERVOIR = 436
WATERBODY_TYPE_SWAMP_MARSH = 466
WATERBODY_TYPE_CHOICES = (
    (WATERBODY_TYPE_UNKNOWN, 'unknown'),
    (WATERBODY_TYPE_ESTUARY, 'estuary'),
    (WATERBODY_TYPE_ICEMASS, 'ice mass'),
    (WATERBODY_TYPE_LAKE_POND, 'lake/pond'),
    (WATERBODY_TYPE_PLAYA, 'playa'),
    (WATERBODY_TYPE_RESERVOIR, 'reservoir'),
    (WATERBODY_TYPE_SWAMP_MARSH, 'swamp/marsh'),
)
