# Generated by Django 2.2.1 on 2019-05-21 20:49

import aol.photos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lakes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(db_column='filename', upload_to=aol.photos.models.upload_to)),
                ('taken_on', models.DateField(blank=True, db_column='photo_date', null=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='lakes.Lake')),
            ],
            options={
                'ordering': ('lake', 'taken_on'),
            },
        ),
    ]
