# Generated by Django 2.2.2 on 2019-09-24 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lakes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mussel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('machine_name', models.CharField(max_length=30)),
                ('is_scientific_name', models.BooleanField()),
            ],
            options={
                'verbose_name': 'mollusc',
                'ordering': ('machine_name',),
            },
        ),
        migrations.CreateModel(
            name='MusselObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sampled', models.DateField()),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mussel_observations', to='lakes.Lake')),
                ('collecting_agency', models.CharField(max_length=128)),
                ('collection_method', models.CharField(max_length=64)),
                ('mussel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mussels.Mussel')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Non-detect'), (3, 'Detect')], default=2)),
                ('target', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'mollusc observation',
                'ordering': ('-date_sampled',),
                'unique_together': {('lake', 'mussel', 'date_sampled', 'target')},
            },
        ),
    ]
