# Generated by Django 2.2.1 on 2019-05-21 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lakes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mussel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('machine_name', models.CharField(max_length=30)),
                ('is_scientific_name', models.BooleanField()),
            ],
            options={
                'verbose_name': 'mollusc specie',
            },
        ),
        migrations.CreateModel(
            name='ReportingAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'reporting agencies',
            },
        ),
        migrations.CreateModel(
            name='MusselObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_description', models.TextField()),
                ('date_checked', models.DateField()),
                ('approved', models.BooleanField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels.ReportingAgency')),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mussel_observations', to='lakes.Lake')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mussels.Mussel')),
            ],
            options={
                'verbose_name': 'mollusc observation',
            },
        ),
    ]
