# Generated by Django 2.2.4 on 2019-09-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mussels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedMusselObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Initialized'), (2, 'Loading'), (3, 'Completed'), (4, 'Error')], default=1)),
                ('datafile', models.FileField(upload_to='')),
                ('output', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'imported mollusc datafile',
                'ordering': ('-created_on', '-updated_on'),
            },
        ),
    ]
