# Generated by Django 2.2.2 on 2019-09-19 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lakes', '0009_update_waterbody_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('rank', models.IntegerField(help_text='Defines the order in which items are listed.', verbose_name='Weight')),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='lakes.Lake')),
            ],
            options={
                'ordering': ('lake', 'rank'),
            },
        ),
    ]
