# Generated by Django 2.2.1 on 2019-05-21 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'counties',
            },
        ),
        migrations.CreateModel(
            name='FishingZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odfw', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('title', models.CharField(blank=True, max_length=255)),
                ('aol_page', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField()),
                ('reachcode', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('permanent_id', models.CharField(max_length=64)),
                ('gnis_id', models.CharField(max_length=32)),
                ('gnis_name', models.CharField(max_length=255)),
                ('county_set', models.ManyToManyField(to='lakes.County')),
                ('fishing_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lakes.FishingZone')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lakes.Lake')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
