# Generated by Django 2.2.1 on 2019-05-28 19:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0002_lake_plants'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=3644, verbose_name='Lake geometry')
        ),
    ]
