# Generated by Django 2.2.2 on 2019-08-21 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        ('lakes', '0003_lake_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lake_cover_photo', to='photos.Photo'),
        ),
    ]
