# Generated by Django 2.2.2 on 2019-08-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0005_populate_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='waterbody_type',
            field=models.IntegerField(choices=[(493, 'estuary'), (378, 'ice mass'), (390, 'lake/pond'), (361, 'playa'), (436, 'reservoir'), (466, 'swamp/marsh')], null=True),
        ),
    ]
