# Generated by Django 2.2.4 on 2019-08-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0006_add_waterbody_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lake',
            options={'ordering': ('is_major', 'title')},
        ),
        migrations.AddField(
            model_name='lake',
            name='has_docs',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lake',
            name='has_mussels',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lake',
            name='has_photos',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lake',
            name='has_plants',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lake',
            name='is_major',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
