# Generated by Django 2.2.4 on 2019-08-23 20:20

from django.db import migrations


def initialize_lake_status(apps, schema_editor):
    Lake = apps.get_model('lakes', 'Lake')

    for record in Lake.objects.iterator():
        record.has_docs = record.documents.exists()
        record.has_photos = record.photos.exists()
        record.has_plants = record.plant_observations.exists()
        record.has_mussels = record.mussel_observationss.exists()

        record.is_major = False
        if any([record.aol_page is not None,
                record.has_docs,
                record.has_photos,
                record.has_plants,
                record.has_mussels]):
            record.is_major = True

        record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0007_replace_computed_status_properties'),
    ]

    operations = [
        migrations.RunPython(initialize_lake_status),
    ]
