# Generated by Django 2.2.2 on 2019-09-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0009_update_waterbody_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='has_resources',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
