# Generated by Django 2.2.4 on 2019-09-26 04:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0010_lake_has_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lake',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3644, verbose_name='Lake geometry'),
        ),
    ]
