# Generated by Django 2.2.1 on 2019-05-21 20:49

import aol.documents.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lakes', '0002_lake_plants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=aol.documents.models.upload_to)),
                ('rank', models.IntegerField(help_text='Defines the order in which items are listed.', verbose_name='Weight')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(0, 'Other'), (1, 'Map')])),
                ('friendly_filename', models.CharField(blank=True, help_text='Filename when document is downloaded.', max_length=255)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lakes.Lake')),
            ],
            options={
                'ordering': ('lake', 'rank'),
            },
        ),
    ]
