# Generated by Django 2.2.2 on 2019-09-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.IntegerField(choices=[(1, 'Map'), (2, 'Bathymetry'), (3, 'Basin Statistics'), (4, 'Atlas of Oregon Lakes Page'), (0, 'Other')]),
        ),
    ]
