# Generated by Django 2.2.2 on 2019-09-19 23:27

from django.db import migrations

from aol.documents import enums


def match_document_types(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')

    Document.objects.filter(name='Printable Lake Map').update(type=enums.DOCUMENT_TYPE_MAP)
    Document.objects.filter(name='Basin Statistics').update(type=enums.DOCUMENT_TYPE_BASIN_STATISTICS)
    Document.objects.filter(name='1985 Atlas of Oregon Lakes Page').update(type=enums.DOCUMENT_TYPE_ATLAS_PRINT_PAGE)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_update_doc_types'),
    ]

    operations = [
        migrations.RunPython(match_document_types),
    ]
